plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "E:\\360MoveData\\Users\\Administrator\\Desktop\\library_demo-feature-docs-organized"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]